### ISSUE TITLE
No such file or directory error while running run.sh

### ISSUE THREAD

**Issue by ansarker** [dp-isi/BodyshapeGuided_VTON#1]
```
Traceback (most recent call last):
  File "stage3/stage3_test.py", line 69, in <module>
    [l_im_masked,l_warp_cloth,l_iuv,l_z,l_prev_cloth_mask],[l_name] =next(obj_test_test)
  File "./data/dataloader_test.py", line 248, in generate_data
    warp_cloth, warp_cloth_mask = f_warp_cloth(stage)
  File "./data/dataloader_test.py", line 158, in f_warp_cloth
    temp=np.array(Image.open(st_file_name))
  File "/home/anis/anaconda3/envs/lgtf/lib/python3.6/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './results/stage1/sample/warps/QS121D0N6=QS121D0N6-G11@9=person_whole_front_TO_TW421D060=TW421D060-A11@8=person_half_front_cloth_mask.png'
```

Cannot figure out the error. Could you please elaborate how you keep the data and why `stage3_test.py` reading data from results directory?

**Comment by ansarker** [comment]
So I have gone through the log and found out that on `stage1_test.py` line 10, `import stage1.tps_transform as tps` gives the first error. Here, I look through the codes but the `tps_transform`  is missing. Can you provide it or let me know how can I produce it?
